### ISSUE TITLE
Ability to query orders on the client reference

### ISSUE THREAD

**Issue by seb-koemei** [revdotcom/rev-ruby-sdk#1]
http://www.rev.com/api/ordersgetone allows to get an order information with the Rev reference as key.

That means that a client needs to store the Rev order references corresponding to his own "client_ref" to be able to get the info on the order from the Rev API.

It wold be good to have a way to query the GET order method with the client_ref as key.

**Comment by BlakeHenry** [comment]
We are taking a more active stance with the api and it's related SDKs recently. Expect more on this soon!
