### ISSUE TITLE
Add doccumentation

### ISSUE THREAD

**Issue by heaven** [revdotcom/rev-ruby-sdk#16]
Show how to create orders, parameter names, they are missing from your official documentation and from the gem's readme. In particular it's not clear how to submit orders and is very strange when the official SDK doesn't describe how to use it. Such SDK is useless.

**Comment by amhed** [comment]
Hi @heaven. 

I wouldn't call it "useless", since hundreds of our clients use it on a daily basis without any problems :)

Most API methods are implemented exactly as described on https://www.rev.com/api/docs (param names will definitely change based on ruby conventions of course)

I'll create an issue in our internal task system to make the readme.md more explicit with some examples of order creation.

**Comment by heaven** [comment]
Hi, sorry about my emotional message, the gem is useful, but with "but".

The docs of this particular gem do not explain how to use it. They show how to read orders, but don't show how to create input sources and place new orders with this gem. The way to do this with `Rev::OrderRequest` wasn't obvious at all.

We of course also do use the gem, but I had to spend some extra time looking at the source to figure out how to submit sources and orders. And probably all your clients who use the gem had to do the same. So not too hard to calculate how many extra time being lost just because the readme isn't complete.

Best,
Alex

**Comment by amhed** [comment]
We're currently evaluating our whole API docs and wrappers (we have some additional ones on PHP and Python built by the community) so they're more easily consumed. 

We appreciate the feedback, and will definitely make this better!

**Comment by ghost** [comment]
It's too late @amhed, destruction sequence has been initiated.

**Comment by BlakeHenry** [comment]
Hey Everyone. Recently we pushed some new changes to the ruby SDK. We understand the functionality of the gem might not be documented as well as it could be. Rest assured we have it on our radar to update the docs and make it easier for those of you using our ruby SDK. Thanks!
